### ISSUE TITLE
Please add Me as a Collaborator

### ISSUE THREAD

**Issue by KshitijBaluni** [Archangel354/MovieStage2-Experiment2#1]
Not able to push the changes.

**Comment by Archangel354** [comment]
Good morning Kshitij!
I have added you to the assignees folder.   Thank you very much for your help.   I hope you can now push your changes to Github

**Comment by Archangel354** [comment]
Hi Kishitij,
I added you to Github.   I hope you can push your changes.   Thank you for
your help!

Rob

**Comment by Archangel354** [comment]
Kshitij,
I am going to temporarily unassign you to this repository for now.   I got my local version to work but there is a merge conflict with github that prevents me from pushing my changes to github.

**Comment by Archangel354** [comment]
Well I just got the push to work.   I put you back as an assignee, so let's see if I can continue to push to github.
